# Check Zero Shot

In [ ]:
import numpy as np
import pickle
import sys
sys.path.append("../..")
from src.utils import viz as vz
# load numpy 
test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
test_a_1 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_embeddings.npy")
# test_a_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_all_outputs_2.pkl","rb"))

test_b_1 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_embeddings.npy")
test_b_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_all_outputs_2.pkl","rb"))
test_b_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-TESTING-test-pt_embed_adata.pkl", "rb"))
test_b_4 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-test-pt_all_outputs_2.pkl", "rb"))
test_b_5 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-3501-test-pt_embed_adata.pkl", "rb"))
test_b_6 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs.pkl", "rb")) # -2 IN <CLS>
test_b_7 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_2.pkl", "rb"))   # 0.0 IN <CLS>
# test_4 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_embeddings.npy")
# test_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_all_outputs.pkl","rb"))

test_1 = vz.merge_embeddings(test_1[0])

In [1]:
import pickle

a = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/valid_indices.pkl","rb"))

In [ ]:
(a)

[[7764,
  1998,
  12208,
  13331,
  3848,
  142,
  5272,
  5169,
  15466,
  17485,
  7571,
  6733,
  3791,
  5895,
  4493,
  6700,
  5194,
  5749,
  9394,
  1096,
  15010,
  327,
  16559,
  5495,
  16069,
  13885,
  9618,
  5810,
  11657,
  8532,
  11672,
  14512,
  1409,
  739,
  7867,
  12833,
  7223,
  2269,
  15413,
  2609,
  16408,
  6425,
  2153,
  8032,
  14337,
  7029,
  7472,
  7755,
  11350,
  6998,
  3007,
  8790,
  4652,
  3004,
  2885,
  8153,
  17148,
  6365,
  8778,
  16556,
  5582,
  6050,
  7367,
  4168,
  16111,
  13643,
  7239,
  666,
  17509,
  2938,
  15794,
  10700,
  6658,
  7415,
  17457,
  3620,
  14952,
  9625,
  2847,
  1495,
  4245,
  16614,
  1826,
  13712,
  6040,
  3565,
  9952,
  5922,
  5120,
  10796,
  14032,
  3596,
  14360,
  6510,
  2268,
  7602,
  4645,
  9628,
  9467,
  4932,
  10389,
  13558,
  11162,
  13716,
  5343,
  4775,
  2863,
  13031,
  7566,
  860,
  11935,
  16412,
  3559,
  6799,
  7166,
  6168,
  1759,
  1785,
  2661,
  10053,
  772,


In [3]:
import scanpy as sc
adata_valid = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_valid_1.h5ad")

In [21]:
adata_valid.X.min()

-2.0

In [4]:
import scanpy as sc
adata_orig = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_orig.h5ad")

In [20]:
import numpy as np
mask = np.isin(adata_orig.obs.ids, adata_valid.obs.ids)
adata_orig[mask].X.max()

array(nan)

In [ ]:
import pandas as pd
adata_subset = adata_orig[mask].X.max()
desired = adata_valid.obs["ids"].tolist()
cat = pd.Categorical(adata_subset.obs["ids"], categories=desired, ordered=True)
adata_subset = adata_subset[adata_subset.obs.assign(_k=cat).sort_values("_k").index, :].copy()


In [ ]:
import sys
sys.path.append("../..")
from src.utils import viz as vz
import pickle
import numpy as np

test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_3.pkl", "rb"))   # 0.0 IN <CLS>
ft_emb_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_4.pkl", "rb"))   # 0.0 IN <CLS>


from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

dist = distance.cdist(test_1, ft_emb_2, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),dist[idxs[:,0], idxs[:,1]])



0.03781865686089214 [0.00380528 0.00383201 0.00439567 ... 0.00386139 0.00283491 0.00316772]
0.03057887051758279 [0.00000000e+00 3.33066907e-16 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]


In [ ]:
test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])
ft_emb_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/method_3-3501-test-ft_embed_adata.pkl", "rb")) # -2 IN <CLS>


dist = distance.cdist(test_1, ft_emb_3.obsm["X_scGPT"], metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),np.mean(dist[idxs[:,0], idxs[:,1]]),dist[idxs[:,0], idxs[:,1]])


In [ ]:
ft_emb_3.shape

(7803, 512)

In [ ]:
distance.cdist(ft_emb,ft_emb, metric="cosine")

array([[0.00000000e+00, 7.24659086e-02, 4.31493784e-02, ...,
        5.84190995e-01, 6.31912488e-01, 6.35170175e-01],
       [7.24659086e-02, 1.11022302e-16, 4.17379465e-02, ...,
        5.84261969e-01, 5.53871905e-01, 5.70207235e-01],
       [4.31493784e-02, 4.17379465e-02, 2.22044605e-16, ...,
        5.99599506e-01, 5.93418321e-01, 6.04420614e-01],
       ...,
       [5.84190995e-01, 5.84261969e-01, 5.99599506e-01, ...,
        0.00000000e+00, 1.39435634e-01, 1.15826118e-01],
       [6.31912488e-01, 5.53871905e-01, 5.93418321e-01, ...,
        1.39435634e-01, 0.00000000e+00, 1.15886476e-02],
       [6.35170175e-01, 5.70207235e-01, 6.04420614e-01, ...,
        1.15826118e-01, 1.15886476e-02, 0.00000000e+00]])

In [13]:
distance.cdist(ft_emb_2,ft_emb_2, metric="cosine")

array([[0.        , 0.07402682, 0.04424553, ..., 0.58788592, 0.63440157,
        0.63624772],
       [0.07402682, 0.        , 0.04366333, ..., 0.58314235, 0.5546783 ,
        0.56937559],
       [0.04424553, 0.04366333, 0.        , ..., 0.60317299, 0.59581863,
        0.60493877],
       ...,
       [0.58788592, 0.58314235, 0.60317299, ..., 0.        , 0.13541452,
        0.11383074],
       [0.63440157, 0.5546783 , 0.59581863, ..., 0.13541452, 0.        ,
        0.01177786],
       [0.63624772, 0.56937559, 0.60493877, ..., 0.11383074, 0.01177786,
        0.        ]])

In [8]:
max(dist[idxs[:,0], idxs[:,1]])

0.03781865686089214

In [5]:
import pickle
gen_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_1.pkl","rb"))

In [45]:

import numpy as np
np.count_nonzero(adata_query.X[0])

3407

In [ ]:
# Manual
gen_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_1.pkl", "rb"))
val_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_1.pkl", "rb"))
manual_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_2.pkl", "rb"))   # 0.0 IN <CLS>

# Manual changed
gen_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_3.pkl", "rb"))
val_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_3.pkl", "rb"))
manual_emb_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_3.pkl", "rb"))   # 0.0 IN <CLS>

# scGPT
gen_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_2.pkl", "rb"))
val_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_2.pkl", "rb"))
scgpt_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_1.pkl", "rb"))   # 0.0 IN <CLS>



In [80]:
manual_emb

array([[-0.03791477,  0.04727682, -0.08842643, ...,  0.03964899,
        -0.04780258, -0.02413424],
       [-0.0300787 ,  0.05320484, -0.09235775, ...,  0.05903852,
        -0.046765  , -0.02132252],
       [-0.02716766,  0.05726336, -0.08150536, ...,  0.04866065,
        -0.04486145, -0.02870571],
       ...,
       [-0.06119252,  0.01640592, -0.0942954 , ..., -0.02247806,
        -0.02978351, -0.04934643],
       [-0.06114848,  0.0245538 , -0.09099831, ..., -0.02424206,
        -0.04659625, -0.04119817],
       [-0.06141688,  0.02483615, -0.09092817, ..., -0.02376318,
        -0.04466689, -0.04251582]], dtype=float32)

In [79]:
manual_emb_3

array([[-0.045158  ,  0.0377593 , -0.07427382, ...,  0.03051918,
        -0.04720969, -0.02214777],
       [-0.03695603,  0.04690555, -0.07933855, ...,  0.05313038,
        -0.04849885, -0.0188033 ],
       [-0.03402665,  0.04965627, -0.06831518, ...,  0.04120196,
        -0.04690394, -0.02567424],
       ...,
       [-0.06597542,  0.00579959, -0.08151054, ..., -0.02016192,
        -0.02044878, -0.04876971],
       [-0.0662518 ,  0.01321454, -0.07826348, ..., -0.02310201,
        -0.03561258, -0.04108498],
       [-0.06640486,  0.01321618, -0.07777499, ..., -0.0223682 ,
        -0.03383278, -0.04246647]], dtype=float32)

In [72]:
scgpt_emb

array([[-0.045158  ,  0.0377593 , -0.07427382, ...,  0.03051918,
        -0.04720969, -0.02214777],
       [-0.03695603,  0.04690555, -0.07933855, ...,  0.05313038,
        -0.04849885, -0.0188033 ],
       [-0.03402665,  0.04965627, -0.06831518, ...,  0.04120196,
        -0.04690394, -0.02567424],
       ...,
       [-0.06597542,  0.00579959, -0.08151054, ..., -0.02016192,
        -0.02044878, -0.04876971],
       [-0.0662518 ,  0.01321454, -0.07826348, ..., -0.02310201,
        -0.03561258, -0.04108498],
       [-0.06640486,  0.01321618, -0.07777499, ..., -0.0223682 ,
        -0.03383278, -0.04246647]], dtype=float32)

In [49]:
d_1 = dict(zip(gen_1[1], val_1[1]))
d_2 = dict(zip(gen_2[1], val_2[1]))

In [61]:
len(set(gen_2[0]))

3409

In [66]:
set(gen_2[1])-set(gen_1[1])

set()

In [69]:
len(set(gen_1[0]))

3409

In [51]:

for i in range(16):
    d_1 = dict(zip(gen_1[1], val_1[1]))
    d_2 = dict(zip(gen_2[1], val_2[1]))

    for k in d_1.keys():
        if d_1[k] != d_2[k]:
            print(f"row {i}",k, d_1[k], d_2[k])

row 0 60695 0.0 -2.0
row 1 60695 0.0 -2.0
row 2 60695 0.0 -2.0
row 3 60695 0.0 -2.0
row 4 60695 0.0 -2.0
row 5 60695 0.0 -2.0
row 6 60695 0.0 -2.0
row 7 60695 0.0 -2.0
row 8 60695 0.0 -2.0
row 9 60695 0.0 -2.0
row 10 60695 0.0 -2.0
row 11 60695 0.0 -2.0
row 12 60695 0.0 -2.0
row 13 60695 0.0 -2.0
row 14 60695 0.0 -2.0
row 15 60695 0.0 -2.0


In [34]:
val_1[0] == val_2[0]

ValueError: operands could not be broadcast together with shapes (3501,) (3447,) 

In [27]:
val_2[0][:1000]

array([-2., 39., 16., 13., 25., 12., 35., 16., 21., 20., 35.,  8., 16.,
       12.,  2., 23., 48., 17., 15., 19., 10.,  3., 11.,  5., 47.,  9.,
       29., 24.,  1., 29., 22., 45., 37., 10., 26., 22., 23., 18., 30.,
       21., 38., 29., 27., 48., 43., 14., 16., 21., 26.,  7., 10., 26.,
       41., 30.,  8., 35.,  2., 14., 11., 26., 36., 38., 22.,  6.,  7.,
       27.,  8., 39., 15., 34.,  5., 42., 19.,  7., 10., 18., 35., 44.,
        6.,  1., 49., 16., 13., 32., 45., 38., 25., 17., 11., 25.,  4.,
       15., 23., 11., 22., 30., 36., 19.,  3., 25.,  3., 10.,  3.,  7.,
        5.,  3.,  7., 11.,  8.,  3., 15., 49., 46., 38.,  2., 44.,  4.,
       12., 45., 19., 12., 19., 10.,  2., 39., 23.,  1., 26.,  7., 15.,
       11., 43., 45.,  4., 37., 10., 35., 22.,  8., 38.,  3., 31., 16.,
       29., 26.,  3., 12., 48.,  6.,  1., 20., 28., 12., 21., 33., 38.,
       16., 36., 32., 19., 12., 15., 24.,  6., 29., 32.,  4., 43., 39.,
       24., 22., 41., 20., 44., 49., 14., 22., 21., 44., 19., 35

In [7]:
gen_1

array([[60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       ...,
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694]])

In [8]:
gen_2

array([[60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       ...,
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 36372, 36562, 36563]])

In [44]:
from scipy.spatial import distance
dist = distance.cdist(test_b_5.obsm["X_scGPT"], test_b_6, metric="cosine")

idxs = np.array([[i,i] for i in range(test_b_4.shape[0])])

dist[idxs[:,0], idxs[:,1]]

array([0.02203371, 0.02126986, 0.02056528, ..., 0.01498833, 0.01628652,
       0.01609157])

In [20]:
import os
run_dir = "/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18"
# query_data_path = "/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-09-12-01/data.h5ad"
query_data_path = os.path.join(run_dir, "adata_test_1.h5ad")

import scanpy as sc

adata_query = sc.read(query_data_path)
