# Check Zero Shot

In [1]:
import scanpy as sc
ad = sc.read("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-14-01/data.h5ad")

In [ ]:
import numpy as np
a = np.zeros((ad.obs.shape[0],100))

ad.layers["zero_shot"] = a

ValueError: Value passed for key 'zero_shot' is of incorrect shape. Values of layers must match dimensions ('obs', 'var') of parent. Value had shape (35626, 16) while it should have had (35626, 20608).

In [7]:
a.shape

(35626, 100)

In [8]:
ad.obs.shape

(35626, 16)

In [69]:
import numpy as np
import pickle
import sys
sys.path.append("../..")
from src.utils import viz as vz
# load numpy 
test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
test_a_1 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_embeddings.npy")
# test_a_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_all_outputs_2.pkl","rb"))

test_b_1 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_embeddings.npy")
test_b_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_all_outputs_2.pkl","rb"))
test_b_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-TESTING-test-pt_embed_adata.pkl", "rb"))
test_b_4 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-test-pt_all_outputs_2.pkl", "rb"))
test_b_5 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-3501-test-pt_embed_adata.pkl", "rb"))
test_b_6 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs.pkl", "rb")) # -2 IN <CLS>
test_b_7 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_2.pkl", "rb"))   # 0.0 IN <CLS>
# test_4 = np.load("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_embeddings.npy")
# test_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-ft_all_outputs.pkl","rb"))

test_1 = vz.merge_embeddings(test_1[0])

/tmp/ipykernel_10914/4133505404.py:7: ResourceWarning: unclosed file <_io.BufferedReader name='/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl'>
  test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
/tmp/ipykernel_10914/4133505404.py:12: ResourceWarning: unclosed file <_io.BufferedReader name='/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_all_outputs_2.pkl'>
  test_b_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/test-pt_all_outputs_2.pkl","rb"))
/tmp/ipykernel_10914/4133505404.py:13: ResourceWarning: unclosed file <_io.BufferedReader name='/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-TESTING-test-pt_embed_adata.pkl'>
  test_b_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_3-TESTING-test-pt_embed_adata.p

In [70]:
from scipy.spatial import distance
dist = distance.cdist(test_1, test_a_1, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


0.030578870440977624 [1.11022302e-16 0.00000000e+00 1.11022302e-16 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]


In [20]:
ls -lrta /aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-24-03


total 1197048
drwxr-xr-x 6 ddalton paloy_g      4096 Sep 25 09:58 ../
drwxr-xr-x 2 ddalton paloy_g      4096 Sep 25 10:01 outputs/
-rw-r--r-- 1 ddalton paloy_g 581574560 Sep 25 12:57 method_3-3501-test-ft_embed_adata.pkl
-rw-r--r-- 1 ddalton paloy_g 581574560 Sep 25 12:58 method_3-3501-test-pt_embed_adata.pkl
-rw-r--r-- 1 ddalton paloy_g    224226 Sep 25 15:55 input_values_3.pkl
-rw-r--r-- 1 ddalton paloy_g    448290 Sep 25 15:55 input_genes_3.pkl
-rw-r--r-- 1 ddalton paloy_g  10391715 Sep 25 18:16 method_2-3501-test-ft_all_outputs_4.pkl
drwxr-xr-x 3 ddalton paloy_g      4096 Sep 26 09:43 ./
-rw-r--r-- 1 ddalton paloy_g  46711528 Sep 26 09:57 method_4-3501-test-ft_embed_adata.pkl


In [1]:
import pickle

a = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/valid_indices.pkl","rb"))

In [ ]:
import sys
sys.path.append("../..")
from src.utils import viz as vz
import pickle
import numpy as np

run_name = "run-25-09-24-03"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/method_3-3501-test-ft_embed_adata.pkl", "rb"))   # 0.0 IN <CLS>
# ft_emb_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_4.pkl", "rb"))   # 0.0 IN <CLS>

from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb.obsm["X_scGPT"], metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


0.2018027562949587 [2.19238208e-04 8.36182433e-05 6.30021746e-05 ... 7.15211951e-05
 1.24979379e-04 7.23735607e-05]


In [5]:
run_name = "run-25-09-28-01"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb_3 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/method_4-3501-test-ft_embed_adata.pkl", "rb"))
ft_emb_3 = vz.merge_embeddings(ft_emb_3)

from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb_3, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


FileNotFoundError: [Errno 2] No such file or directory: '/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-28-01/method_4-3501-test-ft_embed_adata.pkl'

In [57]:
run_name = "run-25-09-26-01"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb_4 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test_replicated.pkl", "rb"))
ft_emb_4 = vz.merge_embeddings(ft_emb_4)

from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb_4, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

/tmp/ipykernel_10914/3695871526.py:3: ResourceWarning: unclosed file <_io.BufferedReader name='/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-26-01/all_outputs_test.pkl'>
  test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
/tmp/ipykernel_10914/3695871526.py:6: ResourceWarning: unclosed file <_io.BufferedReader name='/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-26-01/all_outputs_test_replicated.pkl'>
  ft_emb_4 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test_replicated.pkl", "rb"))


0.1778198945852919 [1.43166649e-07 1.16878015e-05 2.80528878e-06 ... 2.46070125e-07
 1.84766316e-07 1.46771533e-07]


In [ ]:
ls -lrta /aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-26-02

ls: cannot access '/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-26-03': No such file or directory


In [3]:
ls -lrta /aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-26-02

total 1048268
drwxr-xr-x 9 ddalton paloy_g      4096 Sep 26 16:41 ../
drwxr-xr-x 2 ddalton paloy_g      4096 Sep 26 16:41 outputs/
drwxr-xr-x 3 ddalton paloy_g      4096 Sep 26 17:22 ./
-rw-r--r-- 1 ddalton paloy_g  71068686 Sep 26 17:22 all_outputs_test_replicated.pkl
-rw-r--r-- 1 ddalton paloy_g 894302592 Sep 26 18:59 test-pt_embed_adata.pkl
-rw-r--r-- 1 ddalton paloy_g  71833868 Sep 26 18:59 test-ft_all_outputs.pkl
-rw-r--r-- 1 ddalton paloy_g  15980707 Sep 26 18:59 test-pt_all_outputs_2.pkl
-rw-r--r-- 1 ddalton paloy_g  15980707 Sep 26 19:04 test-ft_all_outputs_2.pkl


In [13]:
from scipy.spatial import distance
import numpy as np
import pickle
import sys
sys.path.append("../..")
from src.utils import viz as vz

"""
run_name = "run-25-09-25-01"

set_cls_to_pad = False
include_zero_gene = False
val = 0.22

set_cls_to_pad = True
include_zero_gene = True
0.0033084696508932643 2.869318470819889e-06 [0. 0. 0. ... 0. 0. 0.]


set_cls_to_pad = True
include_zero_gene = False
val = 0.07

set_cls_to_pad = False
include_zero_gene = True
val = 0.22


----

"run-25-09-28-02"
set_cls_to_pad = False
include_zero_gene = False



set_cls_to_pad = True
include_zero_gene = True
val = 0.25


set_cls_to_pad = False
include_zero_gene = False
val = 0.003

"""

run_name = "run-25-09-28-02"
run_name = "run-25-09-13-18"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_valid.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

# ft_emb_1 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft_all_outputs.pkl", "rb"))
# ft_emb_1 = vz.merge_embeddings(ft_emb_1)
ft_emb_2 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft.pkl", "rb"))
# ft_emb_3 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft_all_outputs_replicated.pkl", "rb"))
# ft_emb_3 = vz.merge_embeddings(ft_emb_3)


# dist = distance.cdist(test_1, ft_emb_1, metric="cosine")
# idxs = np.array([[i,i] for i in range(test_1.shape[0])])
# print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


dist = distance.cdist(test_1, ft_emb_2, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),np.mean(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

# dist = distance.cdist(test_1, ft_emb_3, metric="cosine")
# idxs = np.array([[i,i] for i in range(test_1.shape[0])])
# print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


0.6682212798103615 0.0018682138412957226 [0.00000000e+00 1.11022302e-16 1.11022302e-16 ... 1.11022302e-16
 0.00000000e+00 0.00000000e+00]


In [12]:
ls -lrta /aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/

total 7928536
-rw-r--r--  1 ddalton paloy_g  591825544 Sep 22 09:37 test_adata.h5ad
-rw-r--r--  1 ddalton paloy_g   10748032 Sep 22 09:37 test-pt_embeddings.npy
-rw-r--r--  1 ddalton paloy_g   10748032 Sep 22 09:37 test-ft_embeddings.npy
-rw-r--r--  1 ddalton paloy_g 2062616163 Sep 22 09:44 train_adata.h5ad
-rw-r--r--  1 ddalton paloy_g   37488768 Sep 22 09:44 train-pt_embeddings.npy
-rw-r--r--  1 ddalton paloy_g   37488768 Sep 22 09:44 train-ft_embeddings.npy
-rw-r--r--  1 ddalton paloy_g          0 Sep 22 10:52 valid-pt_2_embeddings.npy
-rw-r--r--  1 ddalton paloy_g  229851176 Sep 22 11:00 valid_adata.h5ad
-rw-r--r--  1 ddalton paloy_g    4165760 Sep 22 11:00 valid-pt_embeddings.npy
-rw-r--r--  1 ddalton paloy_g  233244565 Sep 22 11:01 valid-pt_embed_adata.pkl
-rw-r--r--  1 ddalton paloy_g    4165760 Sep 22 11:01 valid-ft_embeddings.npy
-rw-r--r--  1 ddalton paloy_g   18526206 Sep 22 12:12 valid-pt_all_outputs.pkl
-rw-r--r--  1 ddalton paloy_g    4170928 Sep 22 12:12 valid-ft_all_out

In [6]:
np.where(dist[idxs[:,0], idxs[:,1]]>0.5)

(array([ 815, 1268, 1317, 1392, 1509]),)

In [ ]:
"""
pad val true

0.6682212798103615 0.0018682138412957226 [0.00000000e+00 1.11022302e-16 1.11022302e-16 ... 1.11022302e-16
 0.00000000e+00 0.00000000e+00]"""

In [ ]:
"""0.6685461794698104 0.0018109911761720902 [0.00000000e+00 1.11022302e-16 1.11022302e-16 ... 1.11022302e-16
 0.00000000e+00 0.00000000e+00]"""

In [ ]:
"""0.030578870440977624 8.222462311118243e-06 [1.11022302e-16 0.00000000e+00 1.11022302e-16 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]"""

In [8]:
from scipy.spatial import distance
import numpy as np
import pickle
import sys
sys.path.append("../..")
from src.utils import viz as vz
run_name = "run-25-09-26-02"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb_1 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft_all_outputs.pkl", "rb"))
ft_emb_1 = vz.merge_embeddings(ft_emb_1)
ft_emb_2 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft_all_outputs_2.pkl", "rb"))
# ft_emb_3 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/{run_name}/test-ft_all_outputs_replicated.pkl", "rb"))
# ft_emb_3 = vz.merge_embeddings(ft_emb_3)


dist = distance.cdist(test_1, ft_emb_1, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


dist = distance.cdist(test_1, ft_emb_2, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

# dist = distance.cdist(test_1, ft_emb_3, metric="cosine")
# idxs = np.array([[i,i] for i in range(test_1.shape[0])])
# print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


0.005506696458659421 [0.00000000e+00 2.22044605e-16 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
0.0032976703682497943 [0.00000000e+00 2.22044605e-16 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]


In [1]:
from scipy.spatial import distance

run_name = "run-25-09-26-02"
run_name = "run-25-09-13-18"

test_1 = pickle.load(open(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb_4 = pickle.load(open(f"/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/ft_test.pkl", "rb"))
# ft_emb_4 = vz.merge_embeddings(ft_emb_4)

dist = distance.cdist(test_1, ft_emb_4, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


NameError: name 'pickle' is not defined

In [ ]:
ft_emb_1

[{'mlm_output': tensor([[24.2031, 26.4531, 26.8281,  ..., 31.5156, 31.5156, 31.5156],
          [24.4219, 26.8438, 26.4219,  ..., 31.5156, 31.5156, 31.5156],
          [24.6719, 26.1562, 26.5000,  ..., 31.5156, 31.5156, 31.5156],
          ...,
          [28.5781, 28.4531, 29.6406,  ..., 31.5156, 31.5156, 31.5156],
          [28.3281, 28.5000, 28.7812,  ..., 31.5156, 31.5156, 31.5156],
          [28.5156, 28.5938, 29.1875,  ..., 31.5156, 31.5156, 31.5156]],
         dtype=torch.float16),
  'cell_emb': tensor([[-0.4645,  0.1097, -0.1141,  ..., -0.1097, -1.9662,  0.3544],
          [-0.3928,  0.0197, -0.0208,  ..., -0.1562, -1.8988,  0.3101],
          [-0.0356,  0.3071, -0.1286,  ..., -0.0980, -1.9233,  0.2452],
          ...,
          [ 0.6815,  0.0961, -1.1103,  ..., -0.7804, -0.4758, -0.4365],
          [ 0.6687,  0.2131, -0.9993,  ..., -0.7629, -0.5421, -0.4905],
          [ 0.6538,  0.2286, -0.9601,  ..., -0.6964, -0.5329, -0.4938]]),
  'cls_output': tensor([[-0.7432, -3.7852, -2.

In [52]:
ft_emb_4

array([[ 1.0056384 ,  1.721478  , -0.9709495 , ...,  1.9525821 ,
        -0.784105  , -0.3960145 ],
       [ 1.0936033 ,  1.1814783 , -1.7833225 , ...,  1.71316   ,
        -0.6803935 , -0.24315757],
       [ 1.3109622 ,  1.6106977 , -0.5651949 , ...,  1.7795013 ,
        -0.84047234, -0.31053174],
       ...,
       [ 0.47860307,  0.95018816, -0.76723444, ...,  0.70055974,
        -1.4950812 ,  0.07718919],
       [ 0.02808403,  0.28790826, -0.80680007, ...,  0.8674211 ,
        -1.4406618 , -0.0195753 ],
       [-0.00275382,  0.24332602, -0.7754795 , ...,  0.8467768 ,
        -1.3503194 ,  0.00522299]], dtype=float32)

In [47]:
ls -lrta /aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-25-01/

/home/ddalton/Data/old_home/miniconda3/envs/scgpt_2/lib/python3.12/pty.py:95: DeprecationWarning: This process (pid=10914) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()


total 68080
drwxr-xr-x 7 ddalton paloy_g     4096 Sep 26 11:46 ../
drwxr-xr-x 2 ddalton paloy_g     4096 Sep 26 11:46 outputs/
drwxr-xr-x 3 ddalton paloy_g     4096 Sep 26 11:48 ./
-rw-r--r-- 1 ddalton paloy_g 69422263 Sep 26 14:35 method_4-3501-test-ft_embed_adata.pkl


In [18]:
ft_emb_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-24-03/method_4-3501-test-ft_embed_adata.pkl", "rb"))

ft_emb_3 = vz.merge_embeddings(ft_emb_3)

In [19]:
from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb_3, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])


0.20180275551934557 [2.19238233e-04 8.36181995e-05 6.30022017e-05 ... 7.15212056e-05
 1.24979371e-04 7.23735564e-05]


In [ ]:
import sys
sys.path.append("../..")
from src.utils import viz as vz
import pickle
import numpy as np

test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_3.pkl", "rb"))   # 0.0 IN <CLS>
ft_emb_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_4.pkl", "rb"))   # 0.0 IN <CLS>


from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

dist = distance.cdist(test_1, ft_emb_2, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),dist[idxs[:,0], idxs[:,1]])



In [14]:
import scanpy as sc
adata = sc.read(f"/aloy/home/ddalton/projects/scGPT_playground/outputs/{run_name}/adata_test_1.h5ad")


In [17]:
adata.layers["X_binned"].min()

-2

In [12]:
adata.layers["X_binned"].min()

-2

In [ ]:
np.argwhere(adata.layers["X_binned"]==-2)

494

In [2]:
import scanpy as sc
adata_valid = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_valid_1.h5ad")

In [21]:
adata_valid.X.min()

-2.0

In [21]:
import scanpy as sc
adata_orig = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_orig.h5ad")

In [ ]:
adata_ref_train = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_train_1.h5ad")
adata_ref_test = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_test_1.h5ad")
adata_ref_valid = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_valid_1.h5ad")

In [27]:
adata_valid = sc.read("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/adata_valid_1.h5ad")

array(nan)

In [30]:
def subset_adata(adata, adata_ref):
    import numpy as np
    import pandas as pd

    # mask presence in ref
    mask = np.isin(adata.obs.ids, adata_ref.obs.ids)
    adata_subset = adata[mask]

    # re-order to match
    desired = adata_ref.obs["ids"].tolist()
    cat = pd.Categorical(adata_subset.obs["ids"], categories=desired, ordered=True)
    adata_subset = adata_subset[adata_subset.obs.assign(_k=cat).sort_values("_k").index, :].copy()

    assert (adata_subset.obs["ids"].values == adata_ref.obs["ids"].values).all()

    return adata_subset

a1 = subset_adata(adata_orig, adata_train)




In [31]:
a1.X

array([[8.180e+02, 3.480e+02, 1.540e+02, ..., 1.398e+03, 3.949e+03,
        1.900e+01],
       [1.136e+03, 3.400e+02, 4.640e+02, ..., 5.170e+02, 9.710e+02,
        3.000e+00],
       [1.629e+03, 6.670e+02, 1.600e+01, ..., 1.594e+03, 1.895e+03,
        5.300e+01],
       ...,
       [6.600e+02, 7.150e+02, 3.010e+02, ..., 1.319e+03, 1.559e+03,
        1.200e+01],
       [4.020e+02, 3.600e+02, 3.440e+02, ..., 3.210e+02, 1.006e+03,
        6.600e+01],
       [7.360e+02, 5.560e+02, 1.130e+02, ..., 9.700e+02, 3.373e+03,
        6.200e+01]])

In [32]:
adata_train.X

array([[8.180e+02, 3.480e+02, 1.540e+02, ..., 1.398e+03, 3.949e+03,
        1.900e+01],
       [1.136e+03, 3.400e+02, 4.640e+02, ..., 5.170e+02, 9.710e+02,
        3.000e+00],
       [1.629e+03, 6.670e+02, 1.600e+01, ..., 1.594e+03, 1.895e+03,
        5.300e+01],
       ...,
       [6.600e+02, 7.150e+02, 3.010e+02, ..., 1.319e+03, 1.559e+03,
        1.200e+01],
       [4.020e+02, 3.600e+02, 3.440e+02, ..., 3.210e+02, 1.006e+03,
        6.600e+01],
       [7.360e+02, 5.560e+02, 1.130e+02, ..., 9.700e+02, 3.373e+03,
        6.200e+01]])

In [34]:
adata_valid.layers["X_binned"].min()

0

In [48]:
sc.pp.normalize_total(adata_subset, target_sum=1e4) 
sc.pp.log1p(adata_subset)



In [51]:
np.isnan(adata_subset.X).sum()

21006

In [55]:
adata_valid.layers["X_binned"].min()

0

In [42]:
adata_subset.layers

Layers with keys: 

In [40]:
adata_valid.layers["X_log1p"]

array([[1.18616012, 0.76680721, 0.45289941, ..., 0.432232  , 1.58980992,
        0.00534791],
       [0.95815825, 0.73866241, 0.09169395, ..., 0.92380798, 0.66077169,
        0.01272263],
       [0.66944598, 0.31443213, 0.        , ..., 0.74679655, 1.09653401,
        0.08220362],
       ...,
       [0.62576744, 0.81899246, 0.07402695, ..., 1.47818923, 0.76271706,
        2.4186014 ],
       [0.64697316, 0.41767335, 0.08107575, ..., 0.42589965, 2.29170796,
        0.00417213],
       [0.88157815, 0.7801995 , 1.01123151, ..., 0.83606125, 1.70163262,
        0.02359632]])

In [ ]:
import sys
sys.path.append("../..")
from src.utils import viz as vz
import pickle
import numpy as np

test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])

ft_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_3.pkl", "rb"))   # 0.0 IN <CLS>
ft_emb_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-ft_all_outputs_4.pkl", "rb"))   # 0.0 IN <CLS>


from scipy.spatial import distance
dist = distance.cdist(test_1, ft_emb, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]), dist[idxs[:,0], idxs[:,1]])

dist = distance.cdist(test_1, ft_emb_2, metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),dist[idxs[:,0], idxs[:,1]])



0.03781865686089214 [0.00380528 0.00383201 0.00439567 ... 0.00386139 0.00283491 0.00316772]
0.03057887051758279 [0.00000000e+00 3.33066907e-16 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]


In [ ]:
test_1 = pickle.load(open("/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/all_outputs_test.pkl", "rb"))
test_1 = vz.merge_embeddings(test_1[0])
ft_emb_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-23-03/method_3-3501-test-ft_embed_adata.pkl", "rb")) # -2 IN <CLS>


dist = distance.cdist(test_1, ft_emb_3.obsm["X_scGPT"], metric="cosine")
idxs = np.array([[i,i] for i in range(test_1.shape[0])])
print(max(dist[idxs[:,0], idxs[:,1]]),np.mean(dist[idxs[:,0], idxs[:,1]]),dist[idxs[:,0], idxs[:,1]])


In [ ]:
ft_emb_3.shape

(7803, 512)

In [ ]:
distance.cdist(ft_emb,ft_emb, metric="cosine")

array([[0.00000000e+00, 7.24659086e-02, 4.31493784e-02, ...,
        5.84190995e-01, 6.31912488e-01, 6.35170175e-01],
       [7.24659086e-02, 1.11022302e-16, 4.17379465e-02, ...,
        5.84261969e-01, 5.53871905e-01, 5.70207235e-01],
       [4.31493784e-02, 4.17379465e-02, 2.22044605e-16, ...,
        5.99599506e-01, 5.93418321e-01, 6.04420614e-01],
       ...,
       [5.84190995e-01, 5.84261969e-01, 5.99599506e-01, ...,
        0.00000000e+00, 1.39435634e-01, 1.15826118e-01],
       [6.31912488e-01, 5.53871905e-01, 5.93418321e-01, ...,
        1.39435634e-01, 0.00000000e+00, 1.15886476e-02],
       [6.35170175e-01, 5.70207235e-01, 6.04420614e-01, ...,
        1.15826118e-01, 1.15886476e-02, 0.00000000e+00]])

In [13]:
distance.cdist(ft_emb_2,ft_emb_2, metric="cosine")

array([[0.        , 0.07402682, 0.04424553, ..., 0.58788592, 0.63440157,
        0.63624772],
       [0.07402682, 0.        , 0.04366333, ..., 0.58314235, 0.5546783 ,
        0.56937559],
       [0.04424553, 0.04366333, 0.        , ..., 0.60317299, 0.59581863,
        0.60493877],
       ...,
       [0.58788592, 0.58314235, 0.60317299, ..., 0.        , 0.13541452,
        0.11383074],
       [0.63440157, 0.5546783 , 0.59581863, ..., 0.13541452, 0.        ,
        0.01177786],
       [0.63624772, 0.56937559, 0.60493877, ..., 0.11383074, 0.01177786,
        0.        ]])

In [8]:
max(dist[idxs[:,0], idxs[:,1]])

0.03781865686089214

In [5]:
import pickle
gen_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_1.pkl","rb"))

In [45]:

import numpy as np
np.count_nonzero(adata_query.X[0])

3407

In [ ]:
# Manual
gen_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_1.pkl", "rb"))
val_1 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_1.pkl", "rb"))
manual_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_2.pkl", "rb"))   # 0.0 IN <CLS>

# Manual changed
gen_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_3.pkl", "rb"))
val_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_3.pkl", "rb"))
manual_emb_3 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_3.pkl", "rb"))   # 0.0 IN <CLS>

# scGPT
gen_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_genes_2.pkl", "rb"))
val_2 = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/input_values_2.pkl", "rb"))
scgpt_emb = pickle.load(open("/aloy/scratch/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18/method_2-3501-test-pt_all_outputs_1.pkl", "rb"))   # 0.0 IN <CLS>



In [80]:
manual_emb

array([[-0.03791477,  0.04727682, -0.08842643, ...,  0.03964899,
        -0.04780258, -0.02413424],
       [-0.0300787 ,  0.05320484, -0.09235775, ...,  0.05903852,
        -0.046765  , -0.02132252],
       [-0.02716766,  0.05726336, -0.08150536, ...,  0.04866065,
        -0.04486145, -0.02870571],
       ...,
       [-0.06119252,  0.01640592, -0.0942954 , ..., -0.02247806,
        -0.02978351, -0.04934643],
       [-0.06114848,  0.0245538 , -0.09099831, ..., -0.02424206,
        -0.04659625, -0.04119817],
       [-0.06141688,  0.02483615, -0.09092817, ..., -0.02376318,
        -0.04466689, -0.04251582]], dtype=float32)

In [79]:
manual_emb_3

array([[-0.045158  ,  0.0377593 , -0.07427382, ...,  0.03051918,
        -0.04720969, -0.02214777],
       [-0.03695603,  0.04690555, -0.07933855, ...,  0.05313038,
        -0.04849885, -0.0188033 ],
       [-0.03402665,  0.04965627, -0.06831518, ...,  0.04120196,
        -0.04690394, -0.02567424],
       ...,
       [-0.06597542,  0.00579959, -0.08151054, ..., -0.02016192,
        -0.02044878, -0.04876971],
       [-0.0662518 ,  0.01321454, -0.07826348, ..., -0.02310201,
        -0.03561258, -0.04108498],
       [-0.06640486,  0.01321618, -0.07777499, ..., -0.0223682 ,
        -0.03383278, -0.04246647]], dtype=float32)

In [72]:
scgpt_emb

array([[-0.045158  ,  0.0377593 , -0.07427382, ...,  0.03051918,
        -0.04720969, -0.02214777],
       [-0.03695603,  0.04690555, -0.07933855, ...,  0.05313038,
        -0.04849885, -0.0188033 ],
       [-0.03402665,  0.04965627, -0.06831518, ...,  0.04120196,
        -0.04690394, -0.02567424],
       ...,
       [-0.06597542,  0.00579959, -0.08151054, ..., -0.02016192,
        -0.02044878, -0.04876971],
       [-0.0662518 ,  0.01321454, -0.07826348, ..., -0.02310201,
        -0.03561258, -0.04108498],
       [-0.06640486,  0.01321618, -0.07777499, ..., -0.0223682 ,
        -0.03383278, -0.04246647]], dtype=float32)

In [49]:
d_1 = dict(zip(gen_1[1], val_1[1]))
d_2 = dict(zip(gen_2[1], val_2[1]))

In [61]:
len(set(gen_2[0]))

3409

In [66]:
set(gen_2[1])-set(gen_1[1])

set()

In [69]:
len(set(gen_1[0]))

3409

In [51]:

for i in range(16):
    d_1 = dict(zip(gen_1[1], val_1[1]))
    d_2 = dict(zip(gen_2[1], val_2[1]))

    for k in d_1.keys():
        if d_1[k] != d_2[k]:
            print(f"row {i}",k, d_1[k], d_2[k])

row 0 60695 0.0 -2.0
row 1 60695 0.0 -2.0
row 2 60695 0.0 -2.0
row 3 60695 0.0 -2.0
row 4 60695 0.0 -2.0
row 5 60695 0.0 -2.0
row 6 60695 0.0 -2.0
row 7 60695 0.0 -2.0
row 8 60695 0.0 -2.0
row 9 60695 0.0 -2.0
row 10 60695 0.0 -2.0
row 11 60695 0.0 -2.0
row 12 60695 0.0 -2.0
row 13 60695 0.0 -2.0
row 14 60695 0.0 -2.0
row 15 60695 0.0 -2.0


In [34]:
val_1[0] == val_2[0]

ValueError: operands could not be broadcast together with shapes (3501,) (3447,) 

In [27]:
val_2[0][:1000]

array([-2., 39., 16., 13., 25., 12., 35., 16., 21., 20., 35.,  8., 16.,
       12.,  2., 23., 48., 17., 15., 19., 10.,  3., 11.,  5., 47.,  9.,
       29., 24.,  1., 29., 22., 45., 37., 10., 26., 22., 23., 18., 30.,
       21., 38., 29., 27., 48., 43., 14., 16., 21., 26.,  7., 10., 26.,
       41., 30.,  8., 35.,  2., 14., 11., 26., 36., 38., 22.,  6.,  7.,
       27.,  8., 39., 15., 34.,  5., 42., 19.,  7., 10., 18., 35., 44.,
        6.,  1., 49., 16., 13., 32., 45., 38., 25., 17., 11., 25.,  4.,
       15., 23., 11., 22., 30., 36., 19.,  3., 25.,  3., 10.,  3.,  7.,
        5.,  3.,  7., 11.,  8.,  3., 15., 49., 46., 38.,  2., 44.,  4.,
       12., 45., 19., 12., 19., 10.,  2., 39., 23.,  1., 26.,  7., 15.,
       11., 43., 45.,  4., 37., 10., 35., 22.,  8., 38.,  3., 31., 16.,
       29., 26.,  3., 12., 48.,  6.,  1., 20., 28., 12., 21., 33., 38.,
       16., 36., 32., 19., 12., 15., 24.,  6., 29., 32.,  4., 43., 39.,
       24., 22., 41., 20., 44., 49., 14., 22., 21., 44., 19., 35

In [7]:
gen_1

array([[60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       ...,
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694]])

In [8]:
gen_2

array([[60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       ...,
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 60694, 60694, 60694],
       [60695,    12,    13, ..., 36372, 36562, 36563]])

In [44]:
from scipy.spatial import distance
dist = distance.cdist(test_b_5.obsm["X_scGPT"], test_b_6, metric="cosine")

idxs = np.array([[i,i] for i in range(test_b_4.shape[0])])

dist[idxs[:,0], idxs[:,1]]

array([0.02203371, 0.02126986, 0.02056528, ..., 0.01498833, 0.01628652,
       0.01609157])

In [20]:
import os
run_dir = "/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-13-18"
# query_data_path = "/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-09-12-01/data.h5ad"
query_data_path = os.path.join(run_dir, "adata_test_1.h5ad")

import scanpy as sc

adata_query = sc.read(query_data_path)


# Go from raw to processed


In [56]:
adata_valid.X

array([[2.5450e+03, 1.2900e+03, 6.4100e+02, ..., 6.0500e+02, 4.3670e+03,
        6.0000e+00],
       [1.0040e+03, 6.8300e+02, 6.0000e+01, ..., 9.4900e+02, 5.8500e+02,
        8.0000e+00],
       [5.3400e+02, 2.0700e+02, 0.0000e+00, ..., 6.2200e+02, 1.1170e+03,
        4.8000e+01],
       ...,
       [1.0300e+03, 1.5020e+03, 9.1000e+01, ..., 4.0090e+03, 1.3550e+03,
        1.2116e+04],
       [1.0880e+03, 6.2000e+02, 1.0100e+02, ..., 6.3500e+02, 1.0634e+04,
        5.0000e+00],
       [2.3700e+02, 1.9800e+02, 2.9300e+02, ..., 2.1900e+02, 7.5100e+02,
        4.0000e+00]])

In [ ]:

# bin values

# set nans to pad value

# 

In [6]:
a1 = adata_valid.copy()

from scgpt.preprocess import binning  # directly import the scGPT binning util

/home/ddalton/Data/old_home/miniconda3/envs/scgpt_2/lib/python3.12/site-packages/scgpt/model/model.py:19: UserWarning: flash_attn is not installed
  warnings.warn("flash_attn is not installed")
/home/ddalton/Data/old_home/miniconda3/envs/scgpt_2/lib/python3.12/site-packages/torchtext/vocab/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/home/ddalton/Data/old_home/miniconda3/envs/scgpt_2/lib/python3.12/site-packages/torchtext/utils.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `impo

ModuleNotFoundError: No module named 'transformers'

In [57]:
a1 = adata_valid.copy()


In [58]:
adata_subset

AnnData object with n_obs × n_vars = 1779 × 3501
    obs: 'ids', 'dataset', 'dataset_id', 'batch', 'batch_id', 'dsaid', 'tissue', 'n_genes', 'disease', 'celltype', 'disease_study', 'library', 'doid_study', 'doid_id', 'do_id', 'doid_disease', 'celltype_id', 'sample_id', 'test_split_1'
    var: 'gene_symbols', 'gene_name', 'index', 'id_in_vocab'
    uns: 'log1p'

In [37]:
import numpy as np
from anndata import AnnData


def _digitize_with_tiebreak(x: np.ndarray, bins: np.ndarray) -> np.ndarray:
    """
    Digitize with random tie-breaking when bins collapse (like scGPT).
    """
    left_digits = np.digitize(x, bins)
    right_digits = np.digitize(x, bins, right=True)

    # if bins are identical, spread assignments randomly
    rands = np.random.rand(len(x))
    digits = rands * (right_digits - left_digits) + left_digits
    return np.ceil(digits).astype(np.int64)


def independent_binning_scGPT(
    adata: AnnData,
    layer: str = "X",
    n_bins: int = 51,
    result_key: str = "X_binned",
    save_edges: bool = True,
) -> AnnData:
    """
    Reimplementation of scGPT's binning logic:
    - zeros always bin 0
    - non-zeros quantile-binned per row
    - stochastic tie-breaking for flat quantiles
    """
    data = adata.layers[layer] if layer in adata.layers else adata.X
    data = data.toarray() if hasattr(data, "toarray") else np.array(data)

    binned_rows = []
    bin_edges = []

    for row in data:
        if row.max() == 0:  # all zeros
            binned_rows.append(np.zeros_like(row, dtype=np.int64))
            bin_edges.append(np.zeros(n_bins))
            continue

        non_zero_ids = np.nonzero(row)[0]
        non_zero_vals = row[non_zero_ids]

        bins = np.quantile(non_zero_vals, np.linspace(0, 1, n_bins - 1))

        non_zero_digits = _digitize_with_tiebreak(non_zero_vals, bins)

        binned_row = np.zeros_like(row, dtype=np.int64)
        binned_row[non_zero_ids] = non_zero_digits
        binned_rows.append(binned_row)

        bin_edges.append(np.concatenate([[0], bins]))

    adata.layers[result_key] = np.stack(binned_rows)
    if save_edges:
        adata.obsm[f"{result_key}_edges"] = np.stack(bin_edges)

    return adata


In [20]:
a1 = adata_valid.copy()

a1 = adata_subset.copy()

# set nans to 0
mask_nans = np.isnan(a1.X)
a1.X[mask_nans] = 0

# normalize counts
sc.pp.normalize_total(a1, target_sum=1e4)

# log1p 
sc.pp.log1p(a1)

a1.X


array([[1.18616012, 0.76680721, 0.45289941, ..., 0.432232  , 1.58980992,
        0.00534791],
       [0.95815825, 0.73866241, 0.09169395, ..., 0.92380798, 0.66077169,
        0.01272263],
       [0.66944598, 0.31443213, 0.        , ..., 0.74679655, 1.09653401,
        0.08220362],
       ...,
       [0.62576744, 0.81899246, 0.07402695, ..., 1.47818923, 0.76271706,
        2.4186014 ],
       [0.64697316, 0.41767335, 0.08107575, ..., 0.42589965, 2.29170796,
        0.00417213],
       [0.88157815, 0.7801995 , 1.01123151, ..., 0.83606125, 1.70163262,
        0.02359632]])

In [14]:
a1.layers["X_log1p"]

array([[1.18616012, 0.76680721, 0.45289941, ..., 0.432232  , 1.58980992,
        0.00534791],
       [0.95815825, 0.73866241, 0.09169395, ..., 0.92380798, 0.66077169,
        0.01272263],
       [0.66944598, 0.31443213, 0.        , ..., 0.74679655, 1.09653401,
        0.08220362],
       ...,
       [0.62576744, 0.81899246, 0.07402695, ..., 1.47818923, 0.76271706,
        2.4186014 ],
       [0.64697316, 0.41767335, 0.08107575, ..., 0.42589965, 2.29170796,
        0.00417213],
       [0.88157815, 0.7801995 , 1.01123151, ..., 0.83606125, 1.70163262,
        0.02359632]])

In [43]:
independent_binning_scGPT(a1, layer="X", n_bins=51, result_key="X_binned")

AnnData object with n_obs × n_vars = 1779 × 3501
    obs: 'ids', 'dataset', 'dataset_id', 'batch', 'batch_id', 'dsaid', 'tissue', 'n_genes', 'disease', 'celltype', 'disease_study', 'library', 'doid_study', 'doid_id', 'do_id', 'doid_disease', 'celltype_id', 'sample_id', 'test_split_1'
    var: 'gene_symbols', 'gene_name', 'index', 'id_in_vocab'
    uns: 'log1p'
    obsm: 'X_binned_edges'
    layers: 'X_binned'

In [44]:
a1.layers["X_binned"]

array([[35, 24, 15, ..., 14, 42,  2],
       [23, 16,  2, ..., 23, 13,  1],
       [18, 10,  0, ..., 20, 30,  4],
       ...,
       [13, 20,  1, ..., 39, 18, 48],
       [20, 14,  4, ..., 14, 47,  1],
       [22, 20, 26, ..., 21, 41,  2]])

In [39]:
mis_match_idxs = np.argwhere(~(a1.layers["X_binned"] == adata_valid.layers["X_binned"]))

In [45]:
len(mis_match_idxs)

13157

In [40]:
a1.X[mis_match_idxs[0,0], mis_match_idxs[0,1]]

0.007631102489068295

In [41]:
adata_valid.layers["X_log1p"][mis_match_idxs[0,0], mis_match_idxs[0,1]]

0.007631102489068295

In [ ]:
import os
run_dir = "/aloy/home/ddalton/projects/scGPT_playground/outputs/run-25-09-25-01"

adata_valid = sc.read(os.path.join(run_dir, "adata_valid_1.h5ad"))
adata_test = sc.read(os.path.join(run_dir, "adata_test_1.h5ad"))


genes_valid = adata_valid.var["gene_name"].tolist()
genes_test = adata_test.var["gene_name"].tolist()

print(genes_valid == genes_test)

True
